/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;
import org.junit.Test;

import java.io.FileNotFoundException;
import java.io.FileReader;

import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    @Test
    public void testReadData() throws FileNotFoundException {
        GettingData[] before = App.readData("src/test/resources/recentquotes.json");
        Gson gson = new Gson();
        String jsonFormat = gson.toJson(before);
        GettingData[] after = gson.fromJson(jsonFormat, GettingData[].class);
        assertArrayEquals(before, after);
    }
}
