/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.Random;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws FileNotFoundException {
        GettingData[] arrayOfQoutes=readData("app/src/main/resources/recentquotes.json");
        System.out.println(random(arrayOfQoutes));

    }

    public static GettingData[] readData(String path) throws FileNotFoundException {
        FileReader reader = new FileReader(path);
        Gson gson = new Gson();
        GettingData[] quotes = gson.fromJson(reader, GettingData[].class);
        return quotes;
    }

    public static GettingData random(GettingData[] listOfQuotes) throws FileNotFoundException {
        Random rand = new Random();
        int random = rand.nextInt(listOfQuotes.length);
        return listOfQuotes[random];
    }


}
